export const columns = [
  { accessorKey: "slNo", header: "SL" },
  { accessorKey: "dueDays", header: "Due Days" },
  { accessorKey: "concernPerson", header: "Concern Person" },
  { accessorKey: "accountHolder", header: "Account Holder" },
  { accessorKey: "customerStatus", header: "Status" },
  { accessorKey: "date", header: "Date" },
  { accessorKey: "idNo", header: "ID No" },
  { accessorKey: "billNo", header: "Bill No" },
  { accessorKey: "regNo", header: "Reg No" },
  { accessorKey: "vehicleModel", header: "Vehicle Model" },
  { accessorKey: "customerName", header: "Customer Name" },
  { accessorKey: "customerType", header: "Customer Type" },
  { accessorKey: "address", header: "Address" },
  { accessorKey: "billWithVAT", header: "Bill (VAT)" },
  { accessorKey: "billAfterDiscount", header: "Bill After Discount" },
  { accessorKey: "allReceived", header: "All Received" },
  { accessorKey: "balanceDue", header: "Balance Due" },
  { accessorKey: "receivedCheque", header: "Received Cheque" },
  { accessorKey: "ownerMobile", header: "Owner Mobile" },
  { accessorKey: "driverMobile", header: "Driver Mobile" },
];
